name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [11, 12]
        livewire: [3, 4]

    name: Test PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }} and Livewire ${{ matrix.livewire }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer require "livewire/livewire:^${{ matrix.livewire }}.0" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run Tests
        run: composer run test